///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CountryDataModel {
/*
{
  "name": "Afghanistan",
  "flag": "🇦🇫",
  "code": "AF",
  "dial_code": "+93"
}
*/

  String? name;
  String? flag;
  String? code;
  String? dialCode;

  CountryDataModel({
    this.name,
    this.flag,
    this.code,
    this.dialCode,
  });
  CountryDataModel.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    flag = json['flag']?.toString();
    code = json['code']?.toString();
    dialCode = json['dial_code']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['flag'] = flag;
    data['code'] = code;
    data['dial_code'] = dialCode;
    return data;
  }
}
